var question = [
	'Bạn thường ăn gì vào buổi sáng?',	
	'Bạn thường uống gì vào buổi chiều?',
	'Khi vào quán Bar, bạn chơi gì?',
	'Nếu một con kiến cắn bạn, bạn sẽ làm gì?',
	'Bạn dành bao nhiêu thời gian để ngủ trong ngày?',	
	'Bạn thích nuôi thú cưng nào?',
	'Tiệc sinh nhật của mình, bạn thích gì?',
	'Nếu bị điểm C, D, F, bạn sẽ làm gì?',
	'Mỗi khi ra quyết định, bạn có phân vân lắm không?',
	'Khi duyệt Web, bạn sẽ xem Web nào?',
	'Nếu bị phát hiện trốn học đi chơi, bạn sẽ làm gì?',
	'Bạn thích "chém gió" về vấn đề gì?',
	'Khi ai đó khen bạn xinh "voãi", bạn có có suy nghĩ gì?',
	'Khi chơi Dota, đồng đội ngu quá, bạn sẽ làm gì?',
	'Nếu bạn bị trễ hẹn, bạn sẽ?',
	'Bạn có một cuộc hẹn quan trọng và nhân viên phục vụ đổ cà phê lên người bạn, bạn sẽ?'
	];
var answer = [
	'Bánh mì@Cơm sườn', 
	'Cà phê@Nước ngọt', 
	'Cỏ@Đá', 
	'Giết nó@Cho nó cắn',
	'8 tiếng@4 tiếng',
	'Chó@Gà',
	'Ăn rồi ngủ@Được nhiều tiền',
	'Khóc rất nhiều và cố gắng@Mặc kệ, không quan tâm',
	'Run chết được@Bình thường, quyết định xong rồi chết cũng được',
	'Mương 14@BBC Vietnamese',
	'Khóc và xin lỗi, hứa không tái phạm@Xin lỗi không tái phạm và lần sau trốn học cẩn thận hơn',
	'Chính trị xã hội@Chuyện không nên nói nơi công cộng',
	'Mình lúc nào chả xinh@Mắt thằng kia chắc có vấn đề',
	'Chửi thề liên tục@Kiên nhẫn và im lặng',
	'Giận dỗi và ăn vạ@Lát gặp là biết tay!',
	'Không sao, bỏ qua@Chửi vào mặt như chưa từng được chửi'
	];